### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AmorFati2016** [saimanoj18/iros_bshot#1]
hi，i run your code with data form pcl(room_scan1.pcd ,room_scan2.pcd ),but the result have error.

[pcl::SHOTEstimation::createBinDistanceShape] Point 355 has 1 (0.005029%) NaN normals in its neighbourhood
[pcl::SHOTEstimation::createBinDistanceShape] Point 227 has 1 (0.004968%) NaN normals in its neighbourhood
[pcl::SHOTEstimation::createBinDistanceShape] Point 163 has 1 (0.005094%) NaN normals in its neighbourhood
[pcl::SHOTEstimation::createBinDistanceShape] Point 387 has 1 (0.005041%) NaN normals in its neighbourhood
[pcl::SHOTEstimation::createBinDistanceShape] Point 65 has 1 (0.005058%) NaN normals in its neighbourhood

can you ?

best wish.

**Comment by saimanoj18** [comment]
Hi,

This is not an error. These are the warnings that SHOT descriptor generates.

I think the program should still work and find the correspondences if the parameters are suitable for the input point clouds.

**Comment by AmorFati2016** [comment]
hi
i check compute result of normal and  the normal of points have nan nan nan nan .
and the parameters（cb.computeNormal（parma）） become larger, the number of errors decrease, but the error will always exist.
is there a good suggestion to calculate the robustness of the normal vector?

**Comment by saimanoj18** [comment]
From my experience, nan's in normals exist because there will be some points for which normals cannot be estimated or specifically, normal estimation happens only when the number of neighbourhood points are greater than a threshold.

The number of errors decrease with increase in the radius for the very reason that the number of neighbouhood points increase and many points pass through the threshold.

There are various ways to estimate normals robustly, but i found from my experimentation that a normal radius of 0.01m or 0.02 m is the best in the case of Kinect point clouds.
I feel that normal estimation is an important step however, more important is the whole application pipeline. Change in the normal radius does not effect the performance much. So I would suggest you to move ahead with actual application development. If you are focusing on improving normal estimation process, pls have a look at papers that robustly estimate surface normals...however they need more time. 

good luck!

**Comment by AmorFati2016** [comment]
Thanks
Maybe my data type is different. I used the building data obtained from a laser scanner. I tested data for multiple buildings and data from Stanford Bunny. Building data always has  nan value , Bunny data, in the case of mediation parameters,  have good coarse registration. The data of the building may be different from the kinect data, and I want to study the coarse registration and fine registration of the building scan data. Thank you for your reply, and I will continue to study the coarse registration of building data. Thank you. good luck!

**Comment by saimanoj18** [comment]
Yes, for large scare outdoor environments, all the parameters have to be set larger. Some of these parameters include, radius for normal, radius for SHOT descriptor estimation and so on and still you will have many points that stand discretely in large scale point clouds, so nans are inevitable.

Another suggestion is to use a voxel grid filter before passing the point cloud for normals and SHOT estimation which can make things faster.
